-- MySQL Script generated by MySQL Workbench
-- lun 08 nov 2021 09:19:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SOWING_MOON
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SOWING_MOON` ;

-- -----------------------------------------------------
-- Schema SOWING_MOON
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SOWING_MOON` ;
USE `SOWING_MOON` ;

-- -----------------------------------------------------
-- Table `SOWING_MOON`.`FASE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOWING_MOON`.`FASE` (
  `fase` INT NOT NULL,
  PRIMARY KEY (`fase`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOWING_MOON`.`DIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOWING_MOON`.`DIA` (
  `fecha` DATE NOT NULL,
  `fase` INT NOT NULL,
  `dia` INT NOT NULL,
  PRIMARY KEY (`fecha`),
  INDEX `fk_DIA_FASE_idx` (`fase` ASC) VISIBLE,
  CONSTRAINT `fk_DIA_FASE`
    FOREIGN KEY (`fase`)
    REFERENCES `SOWING_MOON`.`FASE` (`fase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOWING_MOON`.`TIPOPLANTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOWING_MOON`.`TIPOPLANTA` (
  `tipo` VARCHAR(40) NOT NULL,
  `descripcion` VARCHAR(700) NOT NULL,
  PRIMARY KEY (`tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOWING_MOON`.`CONSIDERACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOWING_MOON`.`CONSIDERACION` (
  `codigo_consideracion` INT NOT NULL,
  `codigo_fase` INT NOT NULL,
  `codigo_plantas` VARCHAR(40) NOT NULL,
  `descripcion_accion` VARCHAR(700) NOT NULL,
  PRIMARY KEY (`codigo_consideracion`),
  INDEX `fk_CONSIDERACION_FASE1_idx` (`codigo_fase` ASC) VISIBLE,
  INDEX `fk_CONSIDERACION_TIPOPLANTA1_idx` (`codigo_plantas` ASC) VISIBLE,
  CONSTRAINT `fk_CONSIDERACION_FASE1`
    FOREIGN KEY (`codigo_fase`)
    REFERENCES `SOWING_MOON`.`FASE` (`fase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONSIDERACION_TIPOPLANTA1`
    FOREIGN KEY (`codigo_plantas`)
    REFERENCES `SOWING_MOON`.`TIPOPLANTA` (`tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOWING_MOON`.`PLANTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOWING_MOON`.`PLANTA` (
  `nombre` VARCHAR(40) NOT NULL,
  `tipo_planta` VARCHAR(40) NOT NULL,
  `descripcion_planta` VARCHAR(700) NOT NULL,
  `duracion_dias` INT NOT NULL,
  PRIMARY KEY (`nombre`),
  INDEX `fk_PLANTA_TIPOPLANTA1_idx` (`tipo_planta` ASC) VISIBLE,
  CONSTRAINT `fk_PLANTA_TIPOPLANTA1`
    FOREIGN KEY (`tipo_planta`)
    REFERENCES `SOWING_MOON`.`TIPOPLANTA` (`tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOWING_MOON`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOWING_MOON`.`USUARIO` (
  `codigo_usuario` VARCHAR(40) NOT NULL,
  `nombre` VARCHAR(80) NOT NULL,
  `apellido` VARCHAR(80) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `birth` DATE NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codigo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOWING_MOON`.`SIEMBRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOWING_MOON`.`SIEMBRA` (
  `codigo_siembra` VARCHAR(40) NOT NULL,
  `codigo_usuario` VARCHAR(40) NOT NULL,
  `nombre_planta` VARCHAR(40) NOT NULL,
  `fecha` DATE NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `descripcion_siembra` VARCHAR(700) NOT NULL,
  PRIMARY KEY (`codigo_siembra`),
  INDEX `fk_SIEMBRA_PLANTA1_idx` (`nombre_planta` ASC) VISIBLE,
  INDEX `fk_SIEMBRA_USUARIO1_idx` (`codigo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_SIEMBRA_PLANTA1`
    FOREIGN KEY (`nombre_planta`)
    REFERENCES `SOWING_MOON`.`PLANTA` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SIEMBRA_USUARIO1`
    FOREIGN KEY (`codigo_usuario`)
    REFERENCES `SOWING_MOON`.`USUARIO` (`codigo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOWING_MOON`.`CONTACTO_TELEFONO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOWING_MOON`.`CONTACTO_TELEFONO` (
  `codigo_telefono` VARCHAR(40) NOT NULL,
  `codigo_usuario` VARCHAR(40) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`codigo_telefono`),
  INDEX `fk_CONTACTO_TELEFONO_USUARIO1_idx` (`codigo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_CONTACTO_TELEFONO_USUARIO1`
    FOREIGN KEY (`codigo_usuario`)
    REFERENCES `SOWING_MOON`.`USUARIO` (`codigo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOWING_MOON`.`CONTACTO_CORREO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOWING_MOON`.`CONTACTO_CORREO` (
  `codigo_correo` VARCHAR(40) NOT NULL,
  `codigo_usuario` VARCHAR(40) NOT NULL,
  `correo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codigo_correo`),
  INDEX `fk_CONTACTO_TELEFONO_USUARIO1_idx` (`codigo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_CONTACTO_TELEFONO_USUARIO10`
    FOREIGN KEY (`codigo_usuario`)
    REFERENCES `SOWING_MOON`.`USUARIO` (`codigo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOWING_MOON`.`PUBLICACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOWING_MOON`.`PUBLICACION` (
  `codigo_publicacion` VARCHAR(40) NOT NULL,
  `codigo_usuario` VARCHAR(40) NOT NULL,
  `fecha` DATE NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `publicacion` VARCHAR(2000) NOT NULL,
  PRIMARY KEY (`codigo_publicacion`),
  INDEX `fk_CONTACTO_TELEFONO_USUARIO1_idx` (`codigo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_CONTACTO_TELEFONO_USUARIO100`
    FOREIGN KEY (`codigo_usuario`)
    REFERENCES `SOWING_MOON`.`USUARIO` (`codigo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOWING_MOON`.`COMENTARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOWING_MOON`.`COMENTARIO` (
  `codigo_comentario` VARCHAR(40) NOT NULL,
  `codigo_publicacion` VARCHAR(40) NOT NULL,
  `codigo_usuario` VARCHAR(40) NOT NULL,
  `comentario` VARCHAR(700) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`codigo_comentario`),
  INDEX `fk_CONTACTO_TELEFONO_USUARIO1_idx` (`codigo_usuario` ASC) VISIBLE,
  INDEX `fk_COMENTARIO_PUBLICACION1_idx` (`codigo_publicacion` ASC) VISIBLE,
  CONSTRAINT `fk_CONTACTO_TELEFONO_USUARIO1000`
    FOREIGN KEY (`codigo_usuario`)
    REFERENCES `SOWING_MOON`.`USUARIO` (`codigo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMENTARIO_PUBLICACION1`
    FOREIGN KEY (`codigo_publicacion`)
    REFERENCES `SOWING_MOON`.`PUBLICACION` (`codigo_publicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
INSERT_METHOD = NO;


-- -----------------------------------------------------
-- Table `SOWING_MOON`.`LIKE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOWING_MOON`.`LIKE` (
  `codigo_like` VARCHAR(40) NOT NULL,
  `codigo_usuario` VARCHAR(40) NOT NULL,
  `codigo_publicacion` VARCHAR(40) NULL,
  `codigo_comentario` VARCHAR(40) NULL,
  `fecha` DATE NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codigo_like`),
  INDEX `fk_CONTACTO_TELEFONO_USUARIO1_idx` (`codigo_usuario` ASC) VISIBLE,
  INDEX `fk_LIKE_PUBLICACION1_idx` (`codigo_publicacion` ASC) VISIBLE,
  INDEX `fk_LIKE_COMENTARIO1_idx` (`codigo_comentario` ASC) VISIBLE,
  CONSTRAINT `fk_CONTACTO_TELEFONO_USUARIO1001`
    FOREIGN KEY (`codigo_usuario`)
    REFERENCES `SOWING_MOON`.`USUARIO` (`codigo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LIKE_PUBLICACION1`
    FOREIGN KEY (`codigo_publicacion`)
    REFERENCES `SOWING_MOON`.`PUBLICACION` (`codigo_publicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LIKE_COMENTARIO1`
    FOREIGN KEY (`codigo_comentario`)
    REFERENCES `SOWING_MOON`.`COMENTARIO` (`codigo_comentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOWING_MOON`.`ADMIN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOWING_MOON`.`ADMIN` (
  `codigo_admin` VARCHAR(40) NOT NULL,
  `nombre` VARCHAR(80) NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codigo_admin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOWING_MOON`.`AGENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOWING_MOON`.`AGENDA` (
  `codigo_agenda` VARCHAR(40) NOT NULL,
  `codigo_usuario` VARCHAR(40) NOT NULL,
  `codigo_fecha` DATE NOT NULL,
  `codigo_siembra` VARCHAR(40) NULL,
  `descripcion_agenda` VARCHAR(700) NOT NULL,
  PRIMARY KEY (`codigo_agenda`),
  INDEX `fk_AGENDA_USUARIO1_idx` (`codigo_usuario` ASC) VISIBLE,
  INDEX `fk_AGENDA_DIA1_idx` (`codigo_fecha` ASC) VISIBLE,
  INDEX `fk_AGENDA_SIEMBRA1_idx` (`codigo_siembra` ASC) VISIBLE,
  CONSTRAINT `fk_AGENDA_USUARIO1`
    FOREIGN KEY (`codigo_usuario`)
    REFERENCES `SOWING_MOON`.`USUARIO` (`codigo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AGENDA_DIA1`
    FOREIGN KEY (`codigo_fecha`)
    REFERENCES `SOWING_MOON`.`DIA` (`fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AGENDA_SIEMBRA1`
    FOREIGN KEY (`codigo_siembra`)
    REFERENCES `SOWING_MOON`.`SIEMBRA` (`codigo_siembra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
